/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void screen_1_button_4_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen
        screen_create(&ui_manager);
        // load screen
        lv_scr_load_anim(screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) screen_1_button_1_custom_clicked(void) {
}

static void screen_1_button_1_clicked (lv_event_t *e) {
    screen_1_button_1_custom_clicked();
}


void screen_1_create(ui_manager_t *ui)
{
    screen_1_t *scr = screen_1_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_4
    scr->button_4 = lv_btn_create(scr->obj);
    lv_obj_t *button_4_label = lv_label_create(scr->button_4);
    lv_label_set_text(button_4_label, "Change");
    lv_obj_align(button_4_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_4, 321, 195);
    lv_obj_set_size(scr->button_4, 87, 43);

    // Set move animation of scr->button_4
    lv_anim_t anim_button_4_x;
    lv_anim_init(&anim_button_4_x);
    lv_anim_set_var(&anim_button_4_x, scr->button_4);
    lv_anim_set_time(&anim_button_4_x, 1000);
    lv_anim_set_exec_cb(&anim_button_4_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_button_4_x, 0, 321);
    lv_anim_set_path_cb(&anim_button_4_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_4_x);

    lv_anim_t anim_button_4_y;
    lv_anim_init(&anim_button_4_y);
    lv_anim_set_var(&anim_button_4_y, scr->button_4);
    lv_anim_set_time(&anim_button_4_y, 1000);
    lv_anim_set_exec_cb(&anim_button_4_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_button_4_y, 0, 195);
    lv_anim_set_path_cb(&anim_button_4_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_4_y);

    // Set style of scr->button_4
    lv_obj_set_style_bg_color(scr->button_4, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_4, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_4, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->button_4
    lv_obj_add_event_cb(scr->button_4, screen_1_button_4_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Play mygo");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 177, 97);
    lv_obj_set_size(scr->button_1, 127, 79);

    // Set move animation of scr->button_1
    lv_anim_t anim_button_1_x;
    lv_anim_init(&anim_button_1_x);
    lv_anim_set_var(&anim_button_1_x, scr->button_1);
    lv_anim_set_time(&anim_button_1_x, 1000);
    lv_anim_set_exec_cb(&anim_button_1_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_button_1_x, 0, 177);
    lv_anim_set_path_cb(&anim_button_1_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_1_x);

    lv_anim_t anim_button_1_y;
    lv_anim_init(&anim_button_1_y);
    lv_anim_set_var(&anim_button_1_y, scr->button_1);
    lv_anim_set_time(&anim_button_1_y, 1000);
    lv_anim_set_exec_cb(&anim_button_1_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_button_1_y, 0, 97);
    lv_anim_set_path_cb(&anim_button_1_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_1_y);

    // Set style of scr->button_1
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, screen_1_button_1_clicked, LV_EVENT_CLICKED, NULL);


}


