/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_custom_created(void) {
}

void __attribute__((weak)) screen_button_1_custom_clicked(void) {
}

static void screen_button_1_clicked (lv_event_t *e) {
    screen_button_1_custom_clicked();
}

static void screen_spinbox_2_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(screen_get(&ui_manager)->spinbox_2);
    }
}

static void screen_spinbox_2_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(screen_get(&ui_manager)->spinbox_2);
    }
}

void __attribute__((weak)) screen_spinbox_2_custom_clicked(void) {
}

static void screen_spinbox_2_clicked (lv_event_t *e) {
    screen_spinbox_2_custom_clicked();
}

static void screen_button_3_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_1
        screen_1_create(&ui_manager);
        // load screen_1
        lv_scr_load_anim(screen_1_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, ui_manager.auto_del);
    }
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Send");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 311, 72);
    lv_obj_set_size(scr->button_1, 106, 95);

    // Set move animation of scr->button_1
    lv_anim_t anim_button_1_x;
    lv_anim_init(&anim_button_1_x);
    lv_anim_set_var(&anim_button_1_x, scr->button_1);
    lv_anim_set_time(&anim_button_1_x, 1000);
    lv_anim_set_exec_cb(&anim_button_1_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_button_1_x, 0, 311);
    lv_anim_set_path_cb(&anim_button_1_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_1_x);

    lv_anim_t anim_button_1_y;
    lv_anim_init(&anim_button_1_y);
    lv_anim_set_var(&anim_button_1_y, scr->button_1);
    lv_anim_set_time(&anim_button_1_y, 1000);
    lv_anim_set_exec_cb(&anim_button_1_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_button_1_y, 0, 72);
    lv_anim_set_path_cb(&anim_button_1_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_1_y);

    // Set style of scr->button_1
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, screen_button_1_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "Speed:10.00");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 49, 164);
    lv_obj_set_size(scr->label_1, 161, 33);

    // Set move animation of scr->label_1
    lv_anim_t anim_label_1_x;
    lv_anim_init(&anim_label_1_x);
    lv_anim_set_var(&anim_label_1_x, scr->label_1);
    lv_anim_set_time(&anim_label_1_x, 1000);
    lv_anim_set_exec_cb(&anim_label_1_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_label_1_x, 0, 49);
    lv_anim_set_path_cb(&anim_label_1_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_label_1_x);

    lv_anim_t anim_label_1_y;
    lv_anim_init(&anim_label_1_y);
    lv_anim_set_var(&anim_label_1_y, scr->label_1);
    lv_anim_set_time(&anim_label_1_y, 1000);
    lv_anim_set_exec_cb(&anim_label_1_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_label_1_y, 0, 164);
    lv_anim_set_path_cb(&anim_label_1_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_label_1_y);

    // Set style of scr->label_1
    lv_obj_set_style_bg_color(scr->label_1, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_2
    scr->spinbox_2 = lv_spinbox_create(scr->obj);

    lv_spinbox_set_range(scr->spinbox_2, 0, 10000);
    lv_spinbox_set_step(scr->spinbox_2, 1);
    lv_spinbox_set_digit_format(scr->spinbox_2, 5, 5);
    lv_obj_set_pos(scr->spinbox_2, 89, 195);
    lv_obj_set_size(scr->spinbox_2, 115, 44);

    scr->spinbox_2_left_btn = lv_btn_create(scr->obj);
    lv_obj_set_size(scr->spinbox_2_left_btn, 44, 44);
    lv_obj_align_to(scr->spinbox_2_left_btn, scr->spinbox_2, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_2_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_2_left_btn, screen_spinbox_2_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_2_right_btn = lv_btn_create(scr->obj);
    lv_obj_set_size(scr->spinbox_2_right_btn, 44, 44);
    lv_obj_align_to(scr->spinbox_2_right_btn, scr->spinbox_2, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_2_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_2_right_btn, screen_spinbox_2_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_2
    lv_obj_set_style_text_font(scr->spinbox_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_2, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->spinbox_2_left_btn, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->spinbox_2_left_btn, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(scr->spinbox_2_right_btn, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->spinbox_2_right_btn, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->spinbox_2
    lv_obj_add_event_cb(scr->spinbox_2, screen_spinbox_2_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, "Offset*100:");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 146, 164);
    lv_obj_set_size(scr->label_2, 124, 31);

    // Set move animation of scr->label_2
    lv_anim_t anim_label_2_x;
    lv_anim_init(&anim_label_2_x);
    lv_anim_set_var(&anim_label_2_x, scr->label_2);
    lv_anim_set_time(&anim_label_2_x, 1000);
    lv_anim_set_exec_cb(&anim_label_2_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_label_2_x, 0, 146);
    lv_anim_set_path_cb(&anim_label_2_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_label_2_x);

    lv_anim_t anim_label_2_y;
    lv_anim_init(&anim_label_2_y);
    lv_anim_set_var(&anim_label_2_y, scr->label_2);
    lv_anim_set_time(&anim_label_2_y, 1000);
    lv_anim_set_exec_cb(&anim_label_2_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_label_2_y, 0, 164);
    lv_anim_set_path_cb(&anim_label_2_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_label_2_y);

    // Set style of scr->label_2
    lv_obj_set_style_bg_color(scr->label_2, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(CIRNO_128_q95.jpg));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_style_img_opa(scr->image_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_3, 82, 21);

    // Set move animation of scr->image_3
    lv_anim_t anim_image_3_x;
    lv_anim_init(&anim_image_3_x);
    lv_anim_set_var(&anim_image_3_x, scr->image_3);
    lv_anim_set_time(&anim_image_3_x, 1000);
    lv_anim_set_exec_cb(&anim_image_3_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_image_3_x, 0, 82);
    lv_anim_set_path_cb(&anim_image_3_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_image_3_x);

    lv_anim_t anim_image_3_y;
    lv_anim_init(&anim_image_3_y);
    lv_anim_set_var(&anim_image_3_y, scr->image_3);
    lv_anim_set_time(&anim_image_3_y, 1000);
    lv_anim_set_exec_cb(&anim_image_3_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_image_3_y, 0, 21);
    lv_anim_set_path_cb(&anim_image_3_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_image_3_y);

    // Init scr->button_3
    scr->button_3 = lv_btn_create(scr->obj);
    lv_obj_t *button_3_label = lv_label_create(scr->button_3);
    lv_label_set_text(button_3_label, "Change");
    lv_obj_align(button_3_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_3, 321, 195);
    lv_obj_set_size(scr->button_3, 87, 43);

    // Set move animation of scr->button_3
    lv_anim_t anim_button_3_x;
    lv_anim_init(&anim_button_3_x);
    lv_anim_set_var(&anim_button_3_x, scr->button_3);
    lv_anim_set_time(&anim_button_3_x, 1000);
    lv_anim_set_exec_cb(&anim_button_3_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_button_3_x, 0, 321);
    lv_anim_set_path_cb(&anim_button_3_x, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_3_x);

    lv_anim_t anim_button_3_y;
    lv_anim_init(&anim_button_3_y);
    lv_anim_set_var(&anim_button_3_y, scr->button_3);
    lv_anim_set_time(&anim_button_3_y, 1000);
    lv_anim_set_exec_cb(&anim_button_3_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_button_3_y, 0, 195);
    lv_anim_set_path_cb(&anim_button_3_y, lv_anim_path_overshoot);
    lv_anim_start(&anim_button_3_y);

    // Set style of scr->button_3
    lv_obj_set_style_bg_color(scr->button_3, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_3, lv_color_hex(0x00ff7f), LV_PART_MAIN | LV_STATE_PRESSED);

    // Set event handler of scr->button_3
    lv_obj_add_event_cb(scr->button_3, screen_button_3_clicked, LV_EVENT_CLICKED, NULL);

    screen_custom_created();
}


