/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_1;
    lv_obj_t *label_1;
    lv_obj_t *spinbox_2;
    lv_obj_t *spinbox_2_left_btn;
    lv_obj_t *spinbox_2_right_btn;
    lv_obj_t *label_2;
    lv_obj_t *image_3;
    lv_obj_t *button_3;
} screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_4;
    lv_obj_t *button_1;
} screen_1_t;


typedef struct {
    bool auto_del;
    screen_t screen;
    screen_1_t screen_1;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}

static inline screen_1_t *screen_1_get(ui_manager_t *ui)
{
    return &ui->screen_1;
}


void screen_create(ui_manager_t *ui);
void screen_1_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
