/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#include "custom.h"
#include "data_storage.h"
#include "screen_update.h"
#include "audio_player.h"
#include "serial_comm.h"
#include <rtthread.h>

extern ui_manager_t ui_manager;

void custom_init()
{
    /* Add your codes here */
    uart_init();
    memset(my_data, 0, sizeof(my_data));
    if (read_to_sdcard() < 0) {
        rt_kprintf("Read failed, use default data\n");
    }
    lv_spinbox_set_value(ui_manager.screen.spinbox_2, my_data[0]);
    update_screen();
}


void screen_spinbox_2_custom_clicked(void)  {
    my_data[0] = lv_spinbox_get_value(ui_manager.screen.spinbox_2);
    update_screen();
    write_to_sdcard();
}

void screen_button_1_custom_clicked(void) {
    my_data[0] = lv_spinbox_get_value(ui_manager.screen.spinbox_2);
    sprintf(buf, "Speed: %.2f\n", speed + my_data[0]/100.0);
    rt_kprintf("%s", buf);
    play_wav_async(CLICK_WAV);
    memset(buf, 0, sizeof(buf));
}

void screen_custom_created(void) {
    lv_spinbox_set_value(ui_manager.screen.spinbox_2, my_data[0]);
    update_screen();
}

void screen_1_button_1_custom_clicked(void) {
    play_wav_async(MYGO_WAV);
}